context:
  version: 0.1.0
  python_min: 3.12

package:
  name: gha-update
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/g/gha-update/gha_update-${{ version }}.tar.gz
  sha256: 8c0f55ed7bdc11fb061d67984814fd642bd3a1872028e34c15c913cd59202d53

build:
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
    - gha-update = gha_update._cli:cli
  noarch: python
  number: 0

requirements:
  host:
  - python ${{ python_min }}.*
  - flit <4
  - pip
  run:
  - python >=${{ python_min }}
  - click
  - httpx

tests:
- python:
    imports:
      - gha_update
    pip_check: true
    python_version: ${{ python_min }}.*

about:
  summary: Update GitHub Actions version pins in GitHub workflow files.
  description: |+
    # GitHub Actions Updater

    Update GitHub Actions version pins in GitHub workflow files. Even with grouped,
    monthly updates, Dependabot PRs can still be noisy, especially for smaller or
    stable projects. This tool allows updating pins locally, when the maintainer
    wants to.
  license_file: LICENSE.txt
  license: MIT
  homepage: https://github.com/davidism/gha-update

extra:
  recipe-maintainers:
    - lucascolley
